language: node_js
node_js:
  - "12.7"

branches:
  only:
    - master

before_script:

script:
  - npm run build

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  edge: true
  upload_dir: site
  local_dir: build
